require("prototypes.itemgroup.data")
require("prototypes.item.data")
require("prototypes.entity.data")
require("prototypes.resource.data")
require("prototypes.science.data")
require("prototypes.recipe.data")
require("prototypes.technology.data")
